### ISSUE TITLE
Overview section go away (WYSIWG editor)

### ISSUE THREAD

**Issue by dot-clear** [JackGruber/joplin-plugin-note-overview#12]
[It took me a while to realize in which case the plugin is useful. Your examples in Github and each new update feature from Joplin forum give a wonderful result. Overview a great idea ! Thanks]

Just a little issue : When “Create note overview” is manually executed, the overview section crash if it did in the WYSIWG editor.

## Environment
Plugin version : 1.4.2
Joplin version: 1.8.5
Platform: Windows
OS specifics: Win10

## Steps to reproduce

1. Create an overview note with any overview section like :
```
<!-- note-overview-plugin
search: -due:day+7 iscompleted:0
fields: todo_due, title
sort: todo_due ASC
-->
```
2. Switch to WYSIWG editor
3.  Execute "Create note overview” manually

## Describe what you expected to happen
A least don’t lose the overview section

**Comment by JackGruber** [comment]
Yes, this has to do with the limitations of the editor.

![grafik](https://user-images.githubusercontent.com/24863925/118473426-40398700-b70a-11eb-8db4-c15c77e75bb9.png)
https://joplinapp.org/rich_text_editor/

>For a start, most Markdown plugins will not be compatible. If you open a Markdown note that makes use of such plugin in the Rich Text editor, it is likely you will lose the plugin special formatting.

In this case the HTML comments will be deleted and the note overview section is missing.

A good work arround is to use the `Persistent Editor Layout` plugin and set for all notes the `Rendered Markdown viewer` layout.

Maybe I can add a check that when the WYSIWG is selected the note is not updated on `Create note overview`

**Comment by dot-clear** [comment]
The second option is better (less tag, less plugin and less questions) :-). 
If you could include the two cases to not update the note on `Create note overview` button and on `shortcut` overview.

**Comment by dot-clear** [comment]
Perfect ! If you add a “Support” section like “Persistent Editor Layout” dev, I will make you a little a donation.

**Comment by JackGruber** [comment]
Thanks but not necessary. I use the plugin too much myself :D
