### ISSUE TITLE
OR-Search-Connection not working, only AND

### ISSUE THREAD

**Issue by kai452** [JackGruber/joplin-plugin-note-overview#14]
search: any:1 ...

**Comment by JackGruber** [comment]
Works perfect
![grafik](https://user-images.githubusercontent.com/24863925/125276211-4023c500-e310-11eb-87cf-1858e075095d.png)

**Comment by kai452** [comment]
Thank You very much,

but this one show only one hit, alone notebook Welcome has more than one notes


I tried a lot variations, no success or results that make no sense to me:
search: any:1 notebook:Welcome /"- [ ]"
search: any:0 notebook:Welcome any:1 joplin changelog
...

Wanted a filter for all notes with checkboxes uncompleted AND uncompleted tasks.

Can't see, how it works.
By the way: I'am an experienced developer of database frontends.
SQL is best known, but...

**Comment by JackGruber** [comment]
This is no plugin issue!
The plugin use the Joplin searchfilter!

Nested search queries are currently not supported in Joplin and I think the notebooks filter is always added with `AND` but not sure.https://joplinapp.org/help/#search-filters
![grafik](https://user-images.githubusercontent.com/24863925/125330837-86484b00-e347-11eb-81dd-9e081140e7c3.png)

Just search in the forum or github or create a issue when there is a error in the filter.
