### ISSUE TITLE
error message using README as a note

### ISSUE THREAD

**Issue by lwb52** [JackGruber/joplin-plugin-note-overview#15]
the following text in "Rename fields" creates an error message: "Aliased anchor not found"
```
search: *
fields: updated_time, title
alias: updated_time AS Modified
```
what anchor would solve that? where would it go?

**Comment by JackGruber** [comment]
The problem is the search `*`, Simply put in quotation marks.

```
search: "*"
fields: updated_time, title
alias: updated_time AS Modified
```

**Comment by lwb52** [comment]
Thanks! (I'd never have guessed from the examples…)
