### ISSUE TITLE
Unable to make sort working with notebook name

### ISSUE THREAD

**Issue by yougis** [JackGruber/joplin-plugin-note-overview#16]
I tryied to make sort on field notebook but it seems to not working properly

```
<!-- note-overview-plugin
search: type:todo notebook:Projets
fields: title
sort: title DESC
-->
```
result 

```
<!-- note-overview-plugin
search: type:todo notebook:Projets
fields: notebook
sort: notebook ASC
-->
| notebook |
| --- |
| 2 - Dynamic : Couverture forestière Grand Sud |
| 1 - Bilan grand sud |
| 2 - Dynamic : Couverture forestière Grand Sud |
| Incendies |
```

works as expected with title

**Comment by JackGruber** [comment]
At the moment only Joplin fields can be [sorted](https://github.com/JackGruber/joplin-plugin-note-overview#sort), no [virtual fields](https://github.com/JackGruber/joplin-plugin-note-overview#fields).
