### ISSUE TITLE
first row in the generated table

### ISSUE THREAD

**Issue by lahnix** [JackGruber/joplin-plugin-note-overview#2]
Big thanks for this plugin!
Is there a way to user-customize the first row in the generated table in the future? In my example i would like to change the words "title" to "Aufgabe", "user_created_time" to "Erstellt am" and "updated_time" to "Erledigt". 

| title | user_created_time | updated_time |

**Comment by JackGruber** [comment]
I take it on the ToDo list for enhancements.

**Comment by lahnix** [comment]
Great...thanks in advance!

**Comment by JackGruber** [comment]
Added in [v1.2.0](https://github.com/JackGruber/joplin-plugin-note-overview/releases/tag/v1.2.0)

**Comment by lahnix** [comment]
It's great...big Thanks for your work!
