### ISSUE TITLE
Does not work if over 100 notebooks or orphan notebooks exist.

### ISSUE THREAD

**Issue by ken1kob** [JackGruber/joplin-plugin-note-overview#22]
In the following situations, the note-overview plugin does not process any notes.
- Over 100 notebooks exist.
- Orphan notebooks (notebooks whose parent_id point no existing notebooks) exist.

Observed environment: note-overview 1.5.1 and Joplin 2.1.9 on Windows10

The reason of this bug is obvious from its fix. I'll send a pull request soon.

**Comment by JackGruber** [comment]
Yes the `pageQuery` is incremented multiple times.

You have notebooks whose parent_id points to non-existent notebooks?

**Comment by ken1kob** [comment]
> You have notebooks whose parent_id points to non-existent notebooks?

Yes.
Today is the first day I'm going to use this plugin. But it didn't work for me at first. The reasons are both of the above.

Now. It works with my fix, and I'm enjoying it. 
Thanks for your great plugin!
