### ISSUE TITLE
Stripe note-overview code block from body / excerpt

### ISSUE THREAD

**Issue by JackGruber** [JackGruber/joplin-plugin-note-overview#28]
Remove any note-overview from the body and excerpt output

**Comment by Fantasyfr** [comment]
Did you mean the note-overview-plugin section? If yes is the answer, can you add to line 334 an else section with this line of codes?
`
contentText = contentText.trim().replace(/\s+/g, " ");
contentText = contentText.trim().replace(/(\<\!\-\-\ note-overview-plugin)(.*)(\-\-\>)/g, " ");
contentText = contentText.trim().replace(/(\<\!\-\-endoverview\-\-\>)/g, " ");
`
This will allow a nested search with a non-removed mark-down code.

**Comment by Fantasyfr** [comment]
by the way, you forget to document this very nice feature

**Comment by JackGruber** [comment]
Implemented in v1.6.0
