### ISSUE TITLE
Overview duplicated and texts vanished

### ISSUE THREAD

**Issue by ken1kob** [JackGruber/joplin-plugin-note-overview#29]
## Symptoms and reproduction

The following two relevant bugs are observed in Note overview v1.5.2:

- Vanishing Bug: Texts after the last overview setting and texts after an overview setting without its overview  result are vanished at the next update.
- Duplicating Bug: If some texts exist after the last overview result, the result is duplicated at the next update.

To reproduce the vanishing Bug, create the following note, and then execute `Create note overview`.

```
<!-- note-overview-plugin  
search: title:xxx  
-->  
apple 
```

The result is as below. `apple` is vanished.
```
<!-- note-overview-plugin
search: title:xxx
-->
Note count: 0 
| updated_time | title |
| --- | --- |
<!--endoverview-->
```

To reproduce the duplicating Bug, create the following note (or add a text to the end of the above result), and then execute `Create note overview`.
```
<!-- note-overview-plugin
search: title:xxx
-->
Note count: 0 
| updated_time | title |
| --- | --- |
<!--endoverview-->
orange
```

The result is as below. `orange` is vanished and the overview setting and result are duplicated.
```
<!-- note-overview-plugin
search: title:xxx
-->
Note count: 0 
| updated_time | title |
| --- | --- |
<!--endoverview-->
<!- - note-overview-plugin
search: title:xxx
-->
Note count: 0 
| updated_time | title |
| --- | --- |
<!--endoverview-->
```

## Causes and Fixes

Soon, I'll send a pull request fixing the above bugs. Its code self-explains the causes.

**Comment by aarondodd** [comment]
+1 for getting the PR merged :) I'd love to have todo's relevant to a note generated at the top of a note, but it currently deletes any subsequent content.
