### ISSUE TITLE
I can’t update Note Overview

### ISSUE THREAD

**Issue by dot-clear** [JackGruber/joplin-plugin-note-overview#34]
I can’t update overview plugin since 1.5.2 version.

When I install it from file nothing happens. 

No error in log file :

1. `PluginService: "Installing plugin: ... \io.github.jackgruber.note-overview.jpl` ok
2. `PluginService: "Loading plugin from...` not present

Version 1.5.1 plugin works. No issue installing other plugins.

Environment
---
Plugin version : 1.5.4
Joplin version: 2.5.1 (prod, win32, portable), Same problem with v2.3.5
Platform: Windows
OS specifics: Win10

**Comment by JackGruber** [comment]
Fixed issue in the release script
