### ISSUE TITLE
Add a warning color when a taks is close to a due date

### ISSUE THREAD

**Issue by MHoeller** [JackGruber/joplin-plugin-note-overview#35]
### Story
As a user I like to be indicated before a task is due, so that I can react before the due date.

### Verbose
I would be happy to be able to configure, on the settings page, when a due date comes close. E.g 3 days or 72h (I prefer days)
Also I like to be able to set a color for tasks which are in the time window >= (due date - warning time) and < due date

### Example
Assuming a **waring time of 3 days**, due at Oct 20th, waring color set to orange, overdue set to red
before Oct 17th: no action
after Oct 17th and before due date Oct 20th: **change color to orange**
after Oct 20th: taks overdue change color to red

**Comment by JackGruber** [comment]
I'll add it to the list, but I'm not sure if and when this will be implemented.

**Comment by vyzaj** [comment]
this would be immensely useful if it  was able to be used to color code for tags as well.

**Comment by JackGruber** [comment]
Implemented in v1.6.0
