### ISSUE TITLE
Loss of links with "excerpt" option

### ISSUE THREAD

**Issue by bepolymathe** [JackGruber/joplin-plugin-note-overview#39]
Hi @JackGruber 

Until now, I used "body" a lot to see the content of a note/todo. It's very convenient especially when you have a link to another note at the top of the document. But when I have more text underneath the cell becomes longggggg. 
The "excerpt" option allows to bypass this problem but I noticed that it works by breaking the links. 
Is it possible to keep the links in the excerpt that is displayed in the table?
Thanks again for this wonderful plugin.

**Comment by JackGruber** [comment]
Sorry for the late respons.

Use the following undocumented option:

```
excerpt:
  removemd: false
```
![grafik](https://user-images.githubusercontent.com/24863925/151215543-1a3b2497-94bd-41d7-ab00-cd4f0acd232b.png)
