### ISSUE TITLE
How to create todo overview?

### ISSUE THREAD

**Issue by gerroon** [JackGruber/joplin-plugin-note-overview#4]
Hi

Thanks for this plugin. How do I create an overview that displays todo notes and notes with checkmarks?

thanks

**Comment by JackGruber** [comment]
You can try to search for checkboxes `/"- [ ]"` or open todos `type:todo iscompleted:0`, but a combination of basic search and advanced search is not possible I think.

**Comment by lahnix** [comment]
My simple solution ist to make an overview for all notes in the notebook "Todo". If a todo is done, I move the note in the notebook "Done".

**Comment by gerroon** [comment]
> You can try to search for checkboxes `/"- [ ]"` or open todos `type:todo iscompleted:0`, but a combination of basic search and advanced search is not possible I think.

Thanks, I will try it. I hope you  consider this as a feature request

**Comment by JackGruber** [comment]
The search is based on the Joplin API / function. Therefore, exactly the same search querys as in Joplin can be used, but no more.
