### ISSUE TITLE
"undefined" title of notes.

### ISSUE THREAD

**Issue by Klemet** [JackGruber/joplin-plugin-note-overview#40]
Hello there !

Thank you for your wonderful plugin; I think it adds a lot of functionality to Joplin !

I've been having a small issue, however; I wanted to display the notes returned by the search as a list, with their name, and their body in details tags. However, the title of the note is always giving the mention "undefined".

For example, here is the code for the search:
![image](https://user-images.githubusercontent.com/41070328/142015812-2e8646a8-604e-4ebd-89ae-fac5d5241e73.png)

And here is what is returned:
![image](https://user-images.githubusercontent.com/41070328/142015708-8ca6cbce-ef76-44f2-94ef-10e7be724e46.png)

Would you have a pointer on how to solve this ?

**Comment by JackGruber** [comment]
please specify all fields that you use in fields.

**Comment by Klemet** [comment]
Thanks a lot, @JackGruber ! I'm really sorry that I didn't properly read the sentence explaining it in the README. I should have taken more time to read it.

Just out of curiosity, is there a reason why the example in the README just below this sentence doesn't show both fields used being declared in the `fields` argument (on [this line](https://github.com/JackGruber/joplin-plugin-note-overview/blob/ae1a30026141a39e4c89e504e183eda278bff75e/README.md?plain=1#L205)) ?

**Comment by JackGruber** [comment]
The virtual fields like `notebook` are a litte bit special. 
Since these do not come directly from the Joplin notes table, they do not follow this rule. Therefore, these fields can be used without naming in fields, since they do not need to be loaded first.

**Comment by Klemet** [comment]
That's really cool ! I'm really amazed by the capabilities of the plugin 😄 

Thank you for your patience, and have a nice day !
