### ISSUE TITLE
Sort by size does not sort by size

### ISSUE THREAD

**Issue by wiwwo** [JackGruber/joplin-plugin-note-overview#48]
What am I doing wrong?

```
<!-- note-overview-plugin
search: tag:*
fields: title, size, file_size
sort: size DESC
-->
```

<img width="136" alt="image" src="https://user-images.githubusercontent.com/3930671/164684625-4bc138f3-8c15-4849-b9f2-77c4ad8410de.png">

**Comment by JackGruber** [comment]
Nothing, but sorting by a virtual field is not possible. 
https://github.com/JackGruber/joplin-plugin-note-overview#sort
https://github.com/JackGruber/joplin-plugin-note-overview#fields

**Comment by nonobio** [comment]
Hi,
Damn, I also just used this function to clean up my notes and I also noticed that sorting by size didn't work.
Do you know of a solution that works?
Thanks
