### ISSUE TITLE
Tag filter: `And` with `Any`

### ISSUE THREAD

**Issue by AmonsLintao** [JackGruber/joplin-plugin-note-overview#50]
I already found that I can use `any: 1 tag:a tag:b` to select out notes that have either tag `a` or tag `b`.

But how can I achieve conditions like `tag:c and (tag:a or tag:b)`? I tried `tag:c any:1 tag:a tag:b`, it won't work.

**Comment by JackGruber** [comment]
This is not possible in Joplin at the moment

**Comment by JackGruber** [comment]
The PR was never finished for this function: https://github.com/laurent22/joplin/pull/4653
