### ISSUE TITLE
Overview is not created or updated automatically

### ISSUE THREAD

**Issue by gal064** [JackGruber/joplin-plugin-note-overview#51]
Everything works well when I cmd+shift+p and create the note overview manually.

But the note overview is not built or updated automatically. Setting set to 5 minutes and I also enabled the "update every sync" option and that doesn't work as well.

I'm on mac

**Comment by JackGruber** [comment]
The actuald displayed note is not updated during the background updates, so that no data is overwritten which is currently being entered or edited. Only if the command for updating is used, this note will be updated.

**Comment by gal064** [comment]
Oh cool thanks!

**Comment by gal064** [comment]
Created a pull request to update the readme as I assume this can be a common confusion
