### ISSUE TITLE
File field with resource ID?

### ISSUE THREAD

**Issue by ImportTaste** [JackGruber/joplin-plugin-note-overview#55]
I was wondering if there was a way to list the attached files with their resource ID, and if not, if you'd be willing to add that feature.

**Comment by JackGruber** [comment]
NO there is no option to get the resource IDs of a note. What is the usecase for this?

**Comment by JackGruber** [comment]
Since normally no one works with the IDs I don't see any added value at the monent in implementing them as a field, especially since there are already file and file_size which show the name.
