### ISSUE TITLE
Inconsistent auto-updating

### ISSUE THREAD

**Issue by hynow** [JackGruber/joplin-plugin-note-overview#56]
Hi, thanks for creating this plugin!  I was about to create an issue since one type of search was auto-updating (5 minute interval), but another type was not at all.  This happened multiple times.  But now the opposite has happened, where the one that was not updating before now does update, and the other one does not.  So I don't have any helpful clues.  They are both pretty basic.

``

``

I can't seem to get github to display them correctly, but each is using 3 lines in Joplin.  "search" starts the second line in both cases, and the third line is "-->".  None of the lines have trailing spaces.

**Comment by JackGruber** [comment]
If the note is displayed, it is not updated, only when you trigger a manual update. 
With the automatic update only notes that are not displayed are updated.

**Comment by hynow** [comment]
Thanks! That was the issue.  I have also found that manual update only works in markdown mode, which is fine.  It seems hyperlinked titles can only be clicked in markdown mode as well.  But in rich text mode, clicking does work if you hold Ctrl.
