### ISSUE TITLE
Feature request: Excerpt filter

### ISSUE THREAD

**Issue by ImportTaste** [JackGruber/joplin-plugin-note-overview#59]
Because Joplin doesn't have any regex searching for the body of a note as of yet, I was using this plugin. It does work, but the problem is it has to also list every note that doesn't have an excerpt match.

Could you add a new parameter that excludes any result that doesn't have a matching excerpt?

**Comment by JackGruber** [comment]
Not likely, as this field is not intended for searching notes.
