### ISSUE TITLE
Is there a way to rebuild overviews on demand ?

### ISSUE THREAD

**Issue by chevdor** [JackGruber/joplin-plugin-note-overview#6]
While working on an overview, having the ability to manual trigger a rebuild could be useful.
Is that possible ?

**Comment by JackGruber** [comment]
Yes, use the `Create note overview` in Tools or assign a Keyboard shortcut to it. 
https://github.com/JackGruber/joplin-plugin-note-overview#keyboard-shortcuts

**Comment by chevdor** [comment]
Woo, awesome, thanks for the super quick answer.
I actually thought the "create note overview" was to create  new note with an overview snippet.
I will close this issue but it may help renaming this to "update" or "refresh" not overview.
