### ISSUE TITLE
Cannot combine notebook search with checkbox search

### ISSUE THREAD

**Issue by hynow** [JackGruber/joplin-plugin-note-overview#61]
Searching by notebook works as expected in some situations, for example:

```
<!-- note-overview-plugin
search: due:19700201 iscompleted:0 notebook:Projects
fields: todo_due, title, tags, breadcrumb
alias: todo_due as Due, title as Title, tags as Tags, breadcrumb as Directory
sort: todo_due ASC
-->
```

However, it does not work when combining with the checkbox search.

In the case below, it shows everything in all notebooks.

Did I do something wrong?

```
<!-- note-overview-plugin
search: /"- [ ]" notebook:Projects
fields: created_time, title, excerpt
alias: created_time as Created, title as Title, excerpt as Excerpt
sort: created_time ASC
-->
```

**Comment by JackGruber** [comment]
The `/` enables the basic search and disables the search filters in Joplin. Therefore, no filters can be used for this search, or rather, this text is now searched for.
