### ISSUE TITLE
Markdown code block content gets lost

### ISSUE THREAD

**Issue by Dix0r** [JackGruber/joplin-plugin-note-overview#62]
The code block which I put in the markdown note to create the overview note gets lost sometime, this happens at random! As a result the note does not work anymore to create an updated overview. I did not change any text in the (WYSIWYG) editor.

I need to restore the note to revert back to an earlier version. 

The markdown content to create the overview just dissapears. I'm just left with the outcome (i.e. overview) of the note.

Example what the note / markdown note looks like (with the markdown code block content missing):

| Last edit | tags | Title |
| --- | --- | --- |

| Last edit | tags | Title |
| --- | --- | --- |
| 30/05/2023 10:57 | 1-now | [lorem ipsum](:/5cf254ca848242009ac44776f6b024c8) |
| 01/06/2023 08:33 | 1-now | [blaaa1](:/e3c6d38cc6d6429e802db106883d4d60) |
| 26/05/2023 10:23 | 1-now | [blabla](:/72aae294892c4520a84953982f73d5d2) |

**Comment by JackGruber** [comment]
I'm not sure if only viewing in the WYSIWYG editor results to this behavior, as this deletes the comment block and the noteoverview code block. 
https://github.com/JackGruber/joplin-plugin-note-overview#limitations
