### ISSUE TITLE
Tag Field Displays Nothing

### ISSUE THREAD

**Issue by pvstyps** [JackGruber/joplin-plugin-note-overview#64]
Joplin 2.11.11 with Note Overview 1.6.0. When adding "tags" as one of the fields, a column is created but no tags are displayed for any notes even though most of my notes do have tags.

**Comment by JackGruber** [comment]
I have no `2.11.11` installed, but `2.12.10`. Do you use the Joplin build in tags or the tags from a plugin?
What does the code of the note overview look like?
