### ISSUE TITLE
Possible to query date to present?

### ISSUE THREAD

**Issue by Justin-Lund** [JackGruber/joplin-plugin-note-overview#65]
Is it possible to query files modified from a particular date onwards?

For example, I can do this for everything updated in the past week:

```
<!-- note-overview-plugin
search: updated:day-7
fields: title, updated_time
sort: title DESC
-->
```

But is it possible to do change that search for everything modified from 11/20/2023 onwards?

I tried a handful of queries trying to use the moments filter, but I couldn't get the results I was looking for.

**Comment by JackGruber** [comment]
The plugin use the [Joplin search/search ](https://joplinapp.org/help/apps/search#search-filters) filters for query data.
You can use a date like this: `updated:20231120`

**Comment by Justin-Lund** [comment]
Thank you! I thought that would only show files updated on that exact date, guess I should've tested more. Cheers!
