### ISSUE TITLE
Limit the number of displayed notes

### ISSUE THREAD

**Issue by VSegonne** [JackGruber/joplin-plugin-note-overview#69]
Hi, 
Thank you for this amazing plugin, 

I was wondering if there were a way to apply a limit to the number of displayed notes resulting from the search ? I noticed that the limit was hardcoded up to 50 but couldn't find any option in the yaml config. 

Thank you in advance!

**Comment by JackGruber** [comment]
You want to limit the results? 
Because at the moment there is no hardcoded limit or configuration option, all matching notes from a query would be displayed.

**Comment by JackGruber** [comment]
No this code fetch all needed Tags from the note in blocks of 50 in each loop run. 

I'll see if I add a parameter in the next release
```
limit: 5
```
