### ISSUE TITLE
Multiple excerpts with regexp

### ISSUE THREAD

**Issue by sepremento** [JackGruber/joplin-plugin-note-overview#70]
Say I have notes for books with similar structure. All of the notes contain info about the author, title, amount of pages, etc. I want to create something like an updatable table pulling all this info into a note overview. Right now I can pull out one field with excerpt and regex something like `Author:.*` but not for multiple fields.

If this is possible this feature would be much appreciated. Thank you!

**Comment by JackGruber** [comment]
Duplicate / same idee: https://github.com/JackGruber/joplin-plugin-note-overview/issues/60
