### ISSUE TITLE
Complex search doesn't work

### ISSUE THREAD

**Issue by marph91** [JackGruber/joplin-plugin-note-overview#71]
I have the following search term: `notebook:Watchlist Netflix -"Watch State: watched"`:

- Search only in the notebook `Watchlist`
- Search the term `Netflix`
- Exclude the term `Watch State: watched`

In the usual Joplin search bar, it works. But the plugin throws an error. Here is the complete plugin block:

```
<!-- note-overview-plugin
search: notebook:Watchlist Netflix -"Watch State: watched"
fields: title
sort: title DESC
-->
```

This is the error in the dialog:

```
Noteoverview error
Note: Test

YAML parse error
Nested mappings are not allowed in compact mappings


search: notebook:Watchlist Netflix -"Watch State: watched"
fields: title
sort: title DESC
```

I guess `Watch State: watched` is parsed as key-value mapping, but it's only a string.

**Comment by JackGruber** [comment]
Simply write the search in single quotation marks

```
<!-- note-overview-plugin
search: 'notebook:Watchlist Netflix -"Watch State: watched"'
fields: title
sort: title DESC
-->
```

**Comment by marph91** [comment]
Works. Thanks!
