### ISSUE TITLE
Is it possible to search by a notebook id (as there might be notebook name collisions)

### ISSUE THREAD

**Issue by ivangretsky** [JackGruber/joplin-plugin-note-overview#74]
Good day!

Thanks for the awesome plugin!

I have notebooks with the same name in different places of notebook tree. I need to show listing only of the notes from a certain notebook. This probably does not relate to the plugin itself, but maybe I can get a good advice here)

**Comment by JackGruber** [comment]
According to the Joplin doc no
https://joplinapp.org/help/apps/search/#search-filters
